name: Purge cache

on:
  workflow_dispatch:
  workflow_call:

jobs:
  purge-cache:
    name: Purge cache
    runs-on: ubuntu-latest

    steps:
      - uses: fjogeleit/http-request-action@v1
        with:
          url: "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_API_TOKEN }}/purge_cache"
          method: "POST"
          bearerToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          data: "{ 'purge_everything': true }"
