name: Purge cache

on:
  workflow_dispatch:
  workflow_call:

jobs:
  purge-cache:
    name: Purge cache
    runs-on: ubuntu-latest

    steps:
      - uses: fjogeleit/http-request-action@bf78da14118941f7e940279dd58f67e863cbeff6 # v1
        with:
          url: "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache"
          method: "POST"
          bearerToken: "${{ secrets.CLOUDFLARE_API_TOKEN }}"
          data: '{ "purge_everything": true }'
          retry: 3
