name: Purge cache

on:
  workflow_dispatch:
  workflow_call:

jobs:
  purge-cache:
    name: Purge cache
    runs-on: ubuntu-latest

    steps:
      - uses: fjogeleit/http-request-action@44816be1eabb9c1122d8d775923f39bbe55c67a3 # v1
        with:
          url: "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache"
          method: "POST"
          bearerToken: "${{ secrets.CLOUDFLARE_API_TOKEN }}"
          data: '{ "purge_everything": true }'
          retry: 3
