name: Test

on:
  push:
    branches:
      - renovate/**
  workflow_call:

jobs:
  test:
    name: Unit test
    runs-on: ubuntu-latest

    permissions:
      contents: read
    
    steps:
      - name: Clone repository
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      
      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Test step
        run: "deno task test"
